### ISSUE TITLE
function create fails due to buildpack layer issue

### ISSUE THREAD

**Issue by trisberg** [projectriff/riff#1207]
I'm creating my function using: 

```
riff function create square --local-path ~/workspace/riff/square --artifact square.js
```

I keep getting this error:

```
$ kubectl logs -c user-container square-8ksl6-deployment-6c967fc9cf-w44ql
internal/modules/cjs/loader.js:611
    throw err;
    ^

Error: Cannot find module '/workspace/io.projectriff.node/riff-invoker-node/server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:609:15)
    at Function.Module._load (internal/modules/cjs/loader.js:535:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:797:12)
    at executeUserCode (internal/bootstrap/node.js:526:15)
    at startMainThreadExecution (internal/bootstrap/node.js:439:3)
```

I deleted the repository from Docker Hub but there seems to be some caching somewhere. I think we need to come up with some instructions for how to clear this cache.

**Comment by trisberg** [comment]
Running a cluster build seems to work better

```
riff function create square  --git-repo https://github.com/projectriff-samples/node-square --artifact square.js
```

I'm still seeing the error when running the same local-path build again though, so the caching seems to be local.

**Comment by trisberg** [comment]
Tried building with pack and get the same error:

```
$ ./pack build --clear-cache --publish --path ~/workspace/riff/square --builder projectriff/builder:0.2.0-snapshot-ci-c957e7e83d23 --run-image packs/run:0.0.1-rc.755 trisberg/square
Using user-provided builder image projectriff/builder:0.2.0-snapshot-ci-c957e7e83d23
Pulling builder image projectriff/builder:0.2.0-snapshot-ci-c957e7e83d23 (use --no-pull flag to skip this step)
0.2.0-snapshot-ci-c957e7e83d23: Pulling from projectriff/builder
Digest: sha256:ccd06f1d26f99588fde97bd91e81b7a1ffd348efda89f6281f3d08ac12f6334a
Status: Image is up to date for projectriff/builder:0.2.0-snapshot-ci-c957e7e83d23
Using user-provided run image packs/run:0.0.1-rc.755
Using cache volume pack-cache-05f31fa5fca9469dfdf32a583e785809
Cache volume pack-cache-05f31fa5fca9469dfdf32a583e785809 cleared
===> DETECTING
  ...
[exporter] 2019/04/01 15:48:20 
[exporter] *** Image: trisberg/square@sha256:edeabc624c8a3a9007a063ca66bad3cfeac7b64750f14b97b84db0eacd4ab8ac
Successfully built image trisberg/square

$ docker run -p 8080:8080 trisberg/square
Unable to find image 'trisberg/square:latest' locally
latest: Pulling from trisberg/square
898c46f3b1a1: Already exists 
  ...
a0121c84c545: Pull complete 
Digest: sha256:edeabc624c8a3a9007a063ca66bad3cfeac7b64750f14b97b84db0eacd4ab8ac
Status: Downloaded newer image for trisberg/square:latest
internal/modules/cjs/loader.js:611
    throw err;
    ^

Error: Cannot find module '/workspace/io.projectriff.node/riff-invoker-node/server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:609:15)
    at Function.Module._load (internal/modules/cjs/loader.js:535:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:797:12)
    at executeUserCode (internal/bootstrap/node.js:526:15)
    at startMainThreadExecution (internal/bootstrap/node.js:439:3)
```

**Comment by trisberg** [comment]
Full build log:

```
Aruba:pack trisberg$ riff function create square --local-path ~/workspace/riff/square --artifact square.js
Using user-provided builder image projectriff/builder:0.2.0-snapshot-ci-c957e7e83d23
Pulling builder image projectriff/builder:0.2.0-snapshot-ci-c957e7e83d23 (use --no-pull flag to skip this step)
0.2.0-snapshot-ci-c957e7e83d23: Pulling from projectriff/builder
898c46f3b1a1: Pull complete 
63366dfa0a50: Pull complete 
041d4cd74a92: Pull complete 
6e1bee0f8701: Pull complete 
869da0e46476: Pull complete 
e2af0ac73140: Pull complete 
890186096aea: Pull complete 
1f23a30701c6: Pull complete 
fc5bba5ed9df: Pull complete 
60048cb8980b: Pull complete 
91dcdbdf5e50: Pull complete 
ed14e6f2878e: Pull complete 
4e135e0b12d1: Pull complete 
e80eac5d6b4e: Pull complete 
6593a781bc1e: Pull complete 
fe4b3d49d074: Pull complete 
c771ee59a9a5: Pull complete 
29142a661a0d: Pull complete 
f0712cb9c5a1: Pull complete 
dde1331bf300: Pull complete 
23124017c0bd: Pull complete 
4989810d6185: Pull complete 
Digest: sha256:ccd06f1d26f99588fde97bd91e81b7a1ffd348efda89f6281f3d08ac12f6334a
Status: Downloaded newer image for projectriff/builder:0.2.0-snapshot-ci-c957e7e83d23
Using user-provided run image packs/run:0.0.1-rc.755
Using cache image pack-cache-9f6a3569daa4
===> DETECTING
[detector] 2019/04/01 17:54:04 Trying group of 3...
[detector] 2019/04/01 17:54:04 ======== Results ========
[detector] 2019/04/01 17:54:04 Cloud Foundry OpenJDK Buildpack: pass
[detector] 2019/04/01 17:54:04 Cloud Foundry Build System Buildpack: skip
[detector] 2019/04/01 17:54:04 Java Function Buildpack: fail
[detector] 2019/04/01 17:54:04 Trying group of 3...
[detector] 2019/04/01 17:54:04 ======== Output: NPM Buildpack ========
[detector] no "package.json" found at: /workspace/app/package.json
[detector] 2019/04/01 17:54:04 ======== Results ========
[detector] 2019/04/01 17:54:04 Node.js Buildpack: pass
[detector] 2019/04/01 17:54:04 NPM Buildpack: skip
[detector] 2019/04/01 17:54:04 Node Function Buildpack: pass
===> RESTORING
[restorer] 2019/04/01 17:54:06 cache image 'pack-cache-9f6a3569daa4' not found, nothing to restore
===> ANALYZING
Reading information from previous image for possible re-use
[analyzer] 2019/04/01 17:54:08 writing metadata for uncached layer 'io.projectriff.node:function'
[analyzer] 2019/04/01 17:54:08 writing metadata for uncached layer 'io.projectriff.node:riff-invoker-node'
===> BUILDING
[builder] -----> Node.js Buildpack 0.0.4
[builder] -----> NodeJS 11.9.0: Contributing to layer
[builder]        Downloading from https://nodejs.org/dist/v11.9.0/node-v11.9.0-linux-x64.tar.gz
[builder]        Verifying checksum
[builder]        Expanding to /workspace/org.cloudfoundry.buildpacks.nodejs/node
[builder]        Writing NODE_HOME to shared
[builder]        Writing NODE_ENV to shared
[builder]        Writing NODE_MODULES_CACHE to shared
[builder]        Writing NODE_VERBOSE to shared
[builder]        Writing NPM_CONFIG_PRODUCTION to shared
[builder]        Writing NPM_CONFIG_LOGLEVEL to shared
[builder]        Writing WEB_MEMORY to shared
[builder]        Writing WEB_CONCURRENCY to shared
[builder] 
[builder] -----> Node Function Buildpack 0.1.0-BUILD-SNAPSHOT
[builder] -----> riff Node Invoker 0.1.0: Reusing cached layer
[builder] -----> NodeJS square.js: Reusing cached layer
[builder] -----> Process types:
[builder]        web:      node /workspace/io.projectriff.node/riff-invoker-node/server.js
[builder]        function: node /workspace/io.projectriff.node/riff-invoker-node/server.js
[builder] 
===> EXPORTING
[exporter] 2019/04/01 17:54:17 adding layer 'app' with diffID 'sha256:787df3521b0c393c348b7d3e74ef014aa868e862956b60088f81c0261fa345bc'
[exporter] 2019/04/01 17:54:17 reusing layer 'config' with diffID 'sha256:c7176fcc7ac8edf572c3bac458624d1801c527e0d35fa33f95ea59a1044a4d47'
[exporter] 2019/04/01 17:54:18 reusing layer 'launcher' with diffID 'sha256:7336e39d373301c05eda65aa8640073f95983915894c567cb818668700ded279'
[exporter] 2019/04/01 17:54:18 reusing layer 'org.cloudfoundry.buildpacks.nodejs:node' with diffID 'sha256:1098b725e448f481e96249b29628f201b38ff226f71655215ba3a49366f0b03c'
[exporter] 2019/04/01 17:54:18 reusing layer 'io.projectriff.node:function' with diffID 'sha256:81540fb4cf52f99aa9e0d90477e773d2a8f70462c68c50524b7cb678b61f4b6e'
[exporter] 2019/04/01 17:54:18 reusing layer 'io.projectriff.node:riff-invoker-node' with diffID 'sha256:a2e98d046ca37f571a449af30a179241d1fd2e7caf67fa978e92f2e81938bbd8'
[exporter] 2019/04/01 17:54:18 setting metadata label 'io.buildpacks.lifecycle.metadata'
[exporter] 2019/04/01 17:54:18 setting env var 'PACK_LAYERS_DIR=/workspace'
[exporter] 2019/04/01 17:54:18 setting env var 'PACK_APP_DIR=/workspace/app'
[exporter] 2019/04/01 17:54:18 setting entrypoint '/lifecycle/launcher'
[exporter] 2019/04/01 17:54:18 setting empty cmd
[exporter] 2019/04/01 17:54:18 writing image
[exporter] 2019/04/01 17:54:18 existing blob: sha256:890186096aea65abd0ed2ee77cfac580dc7fd84bd2a34f6ddbed0adb6f93e986
[exporter] 2019/04/01 17:54:18 existing blob: sha256:1f23a30701c695154a9fd2ac35371e086dac4ddfcafb8e9a400225831f8866a0
[exporter] 2019/04/01 17:54:18 existing blob: sha256:60048cb8980b0538857792e86bd305372837ebfd587c1a58a00faf443240d089
[exporter] 2019/04/01 17:54:18 existing blob: sha256:339c535925dde2ef0520b7baa9001ce43d14958f31a217f2b1855d7787018047
[exporter] 2019/04/01 17:54:18 existing blob: sha256:869da0e46476c97e3be5be0fe11fdc46f9dfdb2ce2bc3698d2970e60d2a2378a
[exporter] 2019/04/01 17:54:18 existing blob: sha256:fc5bba5ed9df3a0eb3fbd88053bf748bab3876ee167b98fa9458172841d01876
[exporter] 2019/04/01 17:54:18 existing blob: sha256:e2af0ac73140597cf13e9b2086aea83829b4826c1da8c218f166955290e5d357
[exporter] 2019/04/01 17:54:18 existing blob: sha256:6e1bee0f8701f0ae53a5129dc82115967ae36faa30d7701b195dfc6ec317a51d
[exporter] 2019/04/01 17:54:18 existing blob: sha256:c52382f35f927227be148ab50b62aa675ed88af4ae1720519fe0f19e46a44867
[exporter] 2019/04/01 17:54:18 existing blob: sha256:898c46f3b1a1f39827ed135f020c32e2038c87ae0690a8fe73d94e5df9e6a2d6
[exporter] 2019/04/01 17:54:18 existing blob: sha256:a0121c84c54575fa6da4719e62c78c4a13604f3d4f1ded5cba7f8e465e9eeb9d
[exporter] 2019/04/01 17:54:18 existing blob: sha256:63366dfa0a5076458e37ebae948bc7823bab256ca27e09ab94d298e37df4c2a3
[exporter] 2019/04/01 17:54:18 existing blob: sha256:041d4cd74a929bc4b66ee955ab5b229de098fa389d1a1fb9565e536d8878e15f
[exporter] 2019/04/01 17:54:19 existing blob: sha256:85e0268853e45958257a837b2020a7186dfb11eb20b82c4bf99e5f751d43cf57
[exporter] 2019/04/01 17:54:19 existing blob: sha256:4cc63fd07f113363f76ffaadd732b9edcd15113ff565f5d8afa3a4f5e782928c
[exporter] 2019/04/01 17:54:19 pushed blob: sha256:bcd00d7d7e8e2d9d1a823064a786210d87770d5494bda41e7c1951423d5295b5
[exporter] 2019/04/01 17:54:19 pushed blob: sha256:9521a8d2d1df6de2d28e41f9bf53d1fb011d369fcd5b7d9a4e94d8f14efaf02d
[exporter] 2019/04/01 17:54:20 index.docker.io/trisberg/square:latest: digest: sha256:7709e0b3745afa411b21af486c48354351541ddeb818aa22591c215d95818165 size: 2855
[exporter] 2019/04/01 17:54:20 
[exporter] *** Image: docker.io/trisberg/square@sha256:7709e0b3745afa411b21af486c48354351541ddeb818aa22591c215d95818165
===> CACHING
[cacher] 2019/04/01 17:54:21 WARNING: image 'pack-cache-9f6a3569daa4' not found or requires authentication to access
[cacher] 2019/04/01 17:54:21 WARNING: image 'pack-cache-9f6a3569daa4' has incompatible 'io.buildpacks.lifecycle.cache.metadata' label
[cacher] 2019/04/01 17:54:21 adding layer 'org.cloudfoundry.buildpacks.nodejs:0e872c288724e7de72eaa89d1fbc29979a60cdc8c4c0bc1ea65339328bbaaf4c' with diffID 'sha256:d4b12fcf13b711878f0c23d5f2e8e3f459bae652c54bfc345b019eb2c6d134f7'
[cacher] 2019/04/01 17:54:21 adding layer 'org.cloudfoundry.buildpacks.nodejs:node' with diffID 'sha256:1098b725e448f481e96249b29628f201b38ff226f71655215ba3a49366f0b03c'
[cacher] 2019/04/01 17:54:22 setting metadata label 'io.buildpacks.lifecycle.cache.metadata'
[cacher] 2019/04/01 17:54:22 writing image
[cacher] 2019/04/01 17:54:24 cache 'pack-cache-9f6a3569daa4@fcf3a0c3a98d9d4aed1c50f7ea1b0caa109138245318d38c0b2c83e53213dd53'

riff function create: built image docker.io/trisberg/square for service square.

riff function create completed successfully
Issue `riff service status square` to see the status of the function
Aruba:pack trisberg$ 
```

**Comment by trisberg** [comment]
The only way I could fix this was to delete the repository on dockerhub, build the function with a different name and then pull that image and tag it with the original name and push that to dockerhub. After this I can build the function with `--local-path`.

**Comment by scothis** [comment]
@trisberg any chance this is no longer an issue now that we're running on pack 0.1.0?

**Comment by trisberg** [comment]
possibly, let me remove it from the 0.3.0 milestone and I'll close it if it doesn't happen again

**Comment by trisberg** [comment]
I just hit something similar with domino and the latest riff build with pack 0.1.0

```
===> EXPORTING
[exporter] adding layer 'app' with diffID 'sha256:9faa808ac52929cad20ca7d872aad9088d5d82aa02709d236a8bc0b07648e6db'
[exporter] adding layer 'config' with diffID 'sha256:cf44337980f6134288892bb30effa9049e9c54a409ebbca9cc978fbc83ca6269'
[exporter] adding layer 'launcher' with diffID 'sha256:7417c05f2e27d60b777911b95a538f0bac23fec8fec4175a499039949781fabc'
[exporter] Error: failed to : layer 'org.cloudfoundry.buildpacks.nodejs:node' is cache=true but has no contents

Error: failed with status code: 7
```

**Comment by trisberg** [comment]
Full log output:

```
domino> riff function create square-node --local-path fun --artifact square.js --wait
Applied default --image="gcr.io/cf-sandbox-trisberg/square-node"
Using user-provided builder image 'projectriff/builder:0.2.0-snapshot-ci-4bcb3aa75da4'
Pulling builder image 'projectriff/builder:0.2.0-snapshot-ci-4bcb3aa75da4' (use --no-pull flag to skip this step)
0.2.0-snapshot-ci-4bcb3aa75da4: Pulling from projectriff/builder
898c46f3b1a1: Already exists
63366dfa0a50: Already exists
041d4cd74a92: Already exists
6e1bee0f8701: Already exists
736a2f2678d0: Already exists
c14514b920d6: Already exists
4e1c50360d2b: Already exists
3091b80d6304: Already exists
c2cb47c11953: Already exists
3982579fd5a8: Already exists
531565c98c9c: Already exists
16d3805d9518: Pulling fs layer
a384ab92cd4c: Pulling fs layer
ba186005d87d: Pulling fs layer
7e43d48b3b50: Pulling fs layer
66e517d5f297: Pulling fs layer
aee2cd7e2ed2: Pulling fs layer
93c91f1b7d68: Pulling fs layer
a9c407174383: Pulling fs layer
e2ea1ee3ddf3: Pulling fs layer
056587cae7e2: Pulling fs layer
7e43d48b3b50: Waiting
66e517d5f297: Waiting
aee2cd7e2ed2: Waiting
93c91f1b7d68: Waiting
e2ea1ee3ddf3: Waiting
056587cae7e2: Waiting
a9c407174383: Waiting
16d3805d9518: Verifying Checksum
16d3805d9518: Download complete
16d3805d9518: Pull complete
ba186005d87d: Verifying Checksum
ba186005d87d: Download complete
7e43d48b3b50: Verifying Checksum
7e43d48b3b50: Download complete
a384ab92cd4c: Verifying Checksum
a384ab92cd4c: Download complete
aee2cd7e2ed2: Verifying Checksum
aee2cd7e2ed2: Download complete
a384ab92cd4c: Pull complete
93c91f1b7d68: Verifying Checksum
93c91f1b7d68: Download complete
ba186005d87d: Pull complete
e2ea1ee3ddf3: Verifying Checksum
e2ea1ee3ddf3: Download complete
a9c407174383: Verifying Checksum
a9c407174383: Download complete
056587cae7e2: Verifying Checksum
056587cae7e2: Download complete
7e43d48b3b50: Pull complete
66e517d5f297: Verifying Checksum
66e517d5f297: Download complete
66e517d5f297: Pull complete
aee2cd7e2ed2: Pull complete
93c91f1b7d68: Pull complete
a9c407174383: Pull complete
e2ea1ee3ddf3: Pull complete
056587cae7e2: Pull complete
Digest: sha256:06be0b2cbd96fcac6bde0d6702dd23fa21be7d5f06a5605bfa697a2ce2d34917
Status: Downloaded newer image for projectriff/builder:0.2.0-snapshot-ci-4bcb3aa75da4
Using user-provided run image 'packs/run:0.1.0'
Using cache image 'pack-cache-b6f5a529d928'
===> DETECTING
[detector] Trying group of 3...
[detector] ======== Results ========
[detector] Cloud Foundry OpenJDK Buildpack: pass
[detector] Cloud Foundry Build System Buildpack: skip
[detector] Java Function Buildpack: fail
[detector] Trying group of 3...
[detector] ======== Output: NPM Buildpack ========
[detector] no "package.json" found at: /workspace/package.json
[detector] ======== Results ========
[detector] Node.js Buildpack: pass
[detector] NPM Buildpack: skip
[detector] Node Function Buildpack: pass
===> RESTORING
[restorer] restoring cached layer 'org.cloudfoundry.buildpacks.nodejs:0e872c288724e7de72eaa89d1fbc29979a60cdc8c4c0bc1ea65339328bbaaf4c'
[restorer] restoring cached layer 'org.cloudfoundry.buildpacks.nodejs:node'
===> ANALYZING
[analyzer] using cached layer 'org.cloudfoundry.buildpacks.nodejs:0e872c288724e7de72eaa89d1fbc29979a60cdc8c4c0bc1ea65339328bbaaf4c'
[analyzer] using cached launch layer 'org.cloudfoundry.buildpacks.nodejs:node'
[analyzer] rewriting metadata for layer 'org.cloudfoundry.buildpacks.nodejs:node'
[analyzer] writing metadata for uncached layer 'io.projectriff.node:function'
[analyzer] writing metadata for uncached layer 'io.projectriff.node:riff-invoker-node'
===> BUILDING
[builder] -----> Node.js Buildpack 0.0.4
[builder] -----> NodeJS 11.9.0: Reusing cached layer
[builder] 
[builder] -----> Node Function Buildpack 0.1.0-BUILD-SNAPSHOT
[builder] -----> riff Node Invoker 0.1.0: Reusing cached layer
[builder] -----> NodeJS square.js: Reusing cached layer
[builder] -----> Process types:
[builder]        web:      node /layers/io.projectriff.node/riff-invoker-node/server.js
[builder]        function: node /layers/io.projectriff.node/riff-invoker-node/server.js
[builder] 
===> EXPORTING
[exporter] adding layer 'app' with diffID 'sha256:9faa808ac52929cad20ca7d872aad9088d5d82aa02709d236a8bc0b07648e6db'
[exporter] adding layer 'config' with diffID 'sha256:cf44337980f6134288892bb30effa9049e9c54a409ebbca9cc978fbc83ca6269'
[exporter] adding layer 'launcher' with diffID 'sha256:7417c05f2e27d60b777911b95a538f0bac23fec8fec4175a499039949781fabc'
[exporter] Error: failed to : layer 'org.cloudfoundry.buildpacks.nodejs:node' is cache=true but has no contents

Error: failed with status code: 7
```

**Comment by trisberg** [comment]
I've also had a build complete successfully but then have the function fail with:

```
Aruba:square-2 trisberg$ k logs square-test-4zdqz-deployment-b8fb9f94-rkz9z -c user-container
internal/modules/cjs/loader.js:611
    throw err;
    ^

Error: Cannot find module '/layers/io.projectriff.node/riff-invoker-node/server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:609:15)
    at Function.Module._load (internal/modules/cjs/loader.js:535:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:797:12)
    at executeUserCode (internal/bootstrap/node.js:526:15)
    at startMainThreadExecution (internal/bootstrap/node.js:439:3)
```

Full build log:

```
$ riff function create square-test --local-path .
Applied default --image="docker.io/trisberg/square-test"
Using user-provided builder image projectriff/builder:0.2.0-snapshot-ci-4bcb3aa75da4
Pulling builder image projectriff/builder:0.2.0-snapshot-ci-4bcb3aa75da4 (use --no-pull flag to skip this step)
0.2.0-snapshot-ci-4bcb3aa75da4: Pulling from projectriff/builder
Digest: sha256:06be0b2cbd96fcac6bde0d6702dd23fa21be7d5f06a5605bfa697a2ce2d34917
Status: Image is up to date for projectriff/builder:0.2.0-snapshot-ci-4bcb3aa75da4
Using user-provided run image packs/run:0.1.0
Using cache image pack-cache-63520c062aa6
===> DETECTING
[detector] Trying group of 3...
[detector] ======== Results ========
[detector] Cloud Foundry OpenJDK Buildpack: pass
[detector] Cloud Foundry Build System Buildpack: skip
[detector] Java Function Buildpack: fail
[detector] Trying group of 3...
[detector] ======== Output: NPM Buildpack ========
[detector] no "package.json" found at: /workspace/package.json
[detector] ======== Results ========
[detector] Node.js Buildpack: pass
[detector] NPM Buildpack: skip
[detector] Node Function Buildpack: pass
===> RESTORING
[restorer] cache image 'pack-cache-63520c062aa6' not found, nothing to restore
===> ANALYZING
[analyzer] writing metadata for uncached layer 'io.projectriff.node:function'
[analyzer] writing metadata for uncached layer 'io.projectriff.node:riff-invoker-node'
===> BUILDING
[builder] -----> Node.js Buildpack 0.0.4
[builder] -----> NodeJS 11.9.0: Contributing to layer
[builder]        Downloading from https://nodejs.org/dist/v11.9.0/node-v11.9.0-linux-x64.tar.gz
[builder]        Verifying checksum
[builder]        Expanding to /layers/org.cloudfoundry.buildpacks.nodejs/node
[builder]        Writing NODE_HOME to shared
[builder]        Writing NODE_ENV to shared
[builder]        Writing NODE_MODULES_CACHE to shared
[builder]        Writing NODE_VERBOSE to shared
[builder]        Writing NPM_CONFIG_PRODUCTION to shared
[builder]        Writing NPM_CONFIG_LOGLEVEL to shared
[builder]        Writing WEB_MEMORY to shared
[builder]        Writing WEB_CONCURRENCY to shared
[builder] 
[builder] -----> Node Function Buildpack 0.1.0-BUILD-SNAPSHOT
[builder] -----> riff Node Invoker 0.1.0: Reusing cached layer
[builder] -----> NodeJS square.js: Reusing cached layer
[builder] -----> Process types:
[builder]        web:      node /layers/io.projectriff.node/riff-invoker-node/server.js
[builder]        function: node /layers/io.projectriff.node/riff-invoker-node/server.js
[builder] 
===> EXPORTING
[exporter] adding layer 'app' with diffID 'sha256:d851b7395e4a810b7677cbcef5925da594aafb25ce85ebfa4159b149074f46a2'
[exporter] adding layer 'config' with diffID 'sha256:cf44337980f6134288892bb30effa9049e9c54a409ebbca9cc978fbc83ca6269'
[exporter] adding layer 'launcher' with diffID 'sha256:7417c05f2e27d60b777911b95a538f0bac23fec8fec4175a499039949781fabc'
[exporter] adding layer 'org.cloudfoundry.buildpacks.nodejs:node' with diffID 'sha256:52c3a02d18e4ead68628d5d5fcb833f54b7005bf925c71f40aa17a438949d431'
[exporter] reusing layer 'io.projectriff.node:function' with diffID 'sha256:f7d33ea91a5275f6b5af0a262c3c15380550486f42bea8759ae0a0498b090aec'
[exporter] reusing layer 'io.projectriff.node:riff-invoker-node' with diffID 'sha256:fa93fae25ce7004dbe072906aea6910bf208c7de0481f8cd424e63bcff9aa045'
[exporter] setting metadata label 'io.buildpacks.lifecycle.metadata'
[exporter] setting env var 'CNB_LAYERS_DIR=/layers'
[exporter] setting env var 'CNB_APP_DIR=/workspace'
[exporter] setting entrypoint '/lifecycle/launcher'
[exporter] setting empty cmd
[exporter] writing image
[exporter] 
[exporter] *** Image: docker.io/trisberg/square-test@sha256:1ccb181cfd3c3d81e6f82f95baf71239f774017e5818455ef01300b0b2b192da
===> CACHING
[cacher] WARNING: image 'pack-cache-63520c062aa6' not found or requires authentication to access
[cacher] WARNING: image 'pack-cache-63520c062aa6' has incompatible 'io.buildpacks.lifecycle.cache.metadata' label
[cacher] adding layer 'org.cloudfoundry.buildpacks.nodejs:0e872c288724e7de72eaa89d1fbc29979a60cdc8c4c0bc1ea65339328bbaaf4c' with diffID 'sha256:18acead142fd52c49704a97bfdfee2f64191abb089ed3a9c805cd4d9180d0235'
[cacher] adding layer 'org.cloudfoundry.buildpacks.nodejs:node' with diffID 'sha256:52c3a02d18e4ead68628d5d5fcb833f54b7005bf925c71f40aa17a438949d431'
[cacher] setting metadata label 'io.buildpacks.lifecycle.cache.metadata'
[cacher] writing image
[cacher] cache 'pack-cache-63520c062aa6@7fd0686a8028259541812a7c182ca1c6d8385fd6ad34e679b018b98eb29b8696'

riff function create completed successfully
Issue `riff service status square-test` to see the status of the function
```

**Comment by trisberg** [comment]
Once we no longer use 0.3.0-snapshot versions of riff and use pack 0.1.0 or later this should not be a problem. The solution so far has to be removing any images that cause troubles from the registry and also local pack-cache images before building again.
