### ISSUE TITLE
CLI panic on `riff publish` i/o timeout

### ISSUE THREAD

**Issue by scothis** [projectriff/riff#358]
```
Posting to http://35.226.252.64:80/requests/fats-uppercase-java
panic: Post http://35.226.252.64:80/requests/fats-uppercase-java: dial tcp 35.226.252.64:80: i/o timeout
goroutine 1 [running]:
github.com/projectriff/riff/riff-cli/cmd.publish(0xc4200187d0, 0xd, 0xc42001881c, 0x2, 0xc4200184b0, 0xb, 0x88a86d, 0xa, 0x7ffd9e961144, 0x13, ...)
	/home/travis/gopath/src/github.com/projectriff/riff/riff-cli/cmd/publish.go:158 +0x544
github.com/projectriff/riff/riff-cli/cmd.Publish.func1(0xc420193680, 0xc420198370, 0x0, 0x5)
	/home/travis/gopath/src/github.com/projectriff/riff/riff-cli/cmd/publish.go:127 +0x536
github.com/projectriff/riff/vendor/github.com/spf13/cobra.(*Command).execute(0xc420193680, 0xc420198320, 0x5, 0x5, 0xc420193680, 0xc420198320)
	/home/travis/gopath/src/github.com/projectriff/riff/vendor/github.com/spf13/cobra/command.go:702 +0x2c6
github.com/projectriff/riff/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4200beb40, 0xc42000c040, 0xc420100bc0, 0xc420100a20)
	/home/travis/gopath/src/github.com/projectriff/riff/vendor/github.com/spf13/cobra/command.go:783 +0x30e
github.com/projectriff/riff/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4200beb40, 0x2, 0xc42016bf50)
	/home/travis/gopath/src/github.com/projectriff/riff/vendor/github.com/spf13/cobra/command.go:736 +0x2b
main.main()
	/home/travis/gopath/src/github.com/projectriff/riff/cli.go:33 +0x51
```

**Comment by ericbottard** [comment]
Can we still reproduce this? Even more so after https://github.com/projectriff/riff/pull/512 is merged?

I'm seeing an error bubble up (even without the above PR) when I tried to publish to eg a shutdown minikube

**Comment by scothis** [comment]
This issue has gone stale, we're on Knative now! Please reopen if still relevant.
