### ISSUE TITLE
riff cli diagnostics obscured by panic during panic

### ISSUE THREAD

**Issue by glyn** [projectriff/riff#397]
When the shell/echo sample is driven concurrently, the riff cli sometimes panics as follows. It seems a HTTP POST failed, but there is no indication of what went wrong.
```
panic: fatal error: malloc deadlock
panic during panic

runtime stack:
runtime.startpanic_m()
	/usr/local/opt/go/libexec/src/runtime/panic.go:693 +0x179
runtime.systemstack(0x0)
	/usr/local/opt/go/libexec/src/runtime/asm_amd64.s:409 +0x79
runtime.mstart()
	/usr/local/opt/go/libexec/src/runtime/proc.go:1170

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/opt/go/libexec/src/runtime/asm_amd64.s:363 fp=0xc420157650 sp=0xc420157648 pc=0x1053ec0
runtime.startpanic()
	/usr/local/opt/go/libexec/src/runtime/panic.go:592 +0x1e fp=0xc420157668 sp=0xc420157650 pc=0x102b33e
runtime.throw(0x1477992, 0xf)
	/usr/local/opt/go/libexec/src/runtime/panic.go:618 +0x74 fp=0xc420157688 sp=0xc420157668 pc=0x102b464
runtime.mallocgc(0x2010, 0x0, 0x1408701, 0x139c43c)
	/usr/local/opt/go/libexec/src/runtime/malloc.go:621 +0x99d fp=0xc420157728 sp=0xc420157688 pc=0x10126bd
runtime.itabAdd(0x1d45058)
	/usr/local/opt/go/libexec/src/runtime/iface.go:122 +0x83 fp=0xc420157778 sp=0xc420157728 pc=0x100f493
runtime.getitab(0x1408740, 0x13db9c0, 0xc420087b01, 0xc420087b80)
	/usr/local/opt/go/libexec/src/runtime/iface.go:70 +0x404 fp=0xc4201577f0 sp=0xc420157778 pc=0x100f314
runtime.assertE2I2(0x1408740, 0x13db9c0, 0xc4201fe170, 0x7, 0xc400000007, 0xc420157880)
	/usr/local/opt/go/libexec/src/runtime/iface.go:592 +0x43 fp=0xc420157820 sp=0xc4201577f0 pc=0x10107d3
runtime.printany(0x13db9c0, 0xc4201fe170)
	/usr/local/opt/go/libexec/src/runtime/error.go:77 +0x69 fp=0xc4201578e0 sp=0xc420157820 pc=0x10077f9
runtime.printpanics(0xc420157968)
	/usr/local/opt/go/libexec/src/runtime/panic.go:420 +0x71 fp=0xc420157900 sp=0xc4201578e0 pc=0x102ab81
panic(0x140d700, 0xc4201b1ec0)
	/usr/local/opt/go/libexec/src/runtime/panic.go:553 +0x3b4 fp=0xc4201579a0 sp=0xc420157900 pc=0x102afc4
github.com/projectriff/riff/riff-cli/cmd.publish(0x14746ed, 0x9, 0xc42001517b, 0x5)
	/Users/gnormington/go/src/github.com/projectriff/riff/riff-cli/cmd/publish.go:138 +0x50b fp=0xc420157ad8 sp=0xc4201579a0 pc=0x1393dfb
github.com/projectriff/riff/riff-cli/cmd.glob..func20(0x16e06a0, 0xc4200f31a0, 0x0, 0x2)
	/Users/gnormington/go/src/github.com/projectriff/riff/riff-cli/cmd/publish.go:119 +0x4c5 fp=0xc420157d20 sp=0xc420157ad8 pc=0x1397225
github.com/projectriff/riff/vendor/github.com/spf13/cobra.(*Command).execute(0x16e06a0, 0xc4200f3180, 0x2, 0x2, 0x16e06a0, 0xc4200f3180)
	/Users/gnormington/go/src/github.com/projectriff/riff/vendor/github.com/spf13/cobra/command.go:702 +0x2c6 fp=0xc420157dc8 sp=0xc420157d20 pc=0x1182816
github.com/projectriff/riff/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x16de280, 0x1, 0x16e0ae0, 0xc420157f68)
	/Users/gnormington/go/src/github.com/projectriff/riff/vendor/github.com/spf13/cobra/command.go:783 +0x2e4 fp=0xc420157ef8 sp=0xc420157dc8 pc=0x1183134
github.com/projectriff/riff/vendor/github.com/spf13/cobra.(*Command).Execute(0x16de280, 0xc42007c058, 0x0)
	/Users/gnormington/go/src/github.com/projectriff/riff/vendor/github.com/spf13/cobra/command.go:736 +0x2b fp=0xc420157f28 sp=0xc420157ef8 pc=0x1182e2b
github.com/projectriff/riff/riff-cli/cmd.Execute()
	/Users/gnormington/go/src/github.com/projectriff/riff/riff-cli/cmd/root.go:47 +0x2d fp=0xc420157f78 sp=0xc420157f28 pc=0x139418d
main.main()
	/Users/gnormington/go/src/github.com/projectriff/riff/cli.go:24 +0x20 fp=0xc420157f88 sp=0xc420157f78 pc=0x1398c20
runtime.main()
	/usr/local/opt/go/libexec/src/runtime/proc.go:198 +0x212 fp=0xc420157fe0 sp=0xc420157f88 pc=0x102cce2
runtime.goexit()
	/usr/local/opt/go/libexec/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc420157fe8 sp=0xc420157fe0 pc=0x1056a31
```

Version info:
```
$ riff version
riff CLI version: 0.0.5-snapshot
riff function invoker version: latest
$ go version
go version go1.10 darwin/amd64
```

Rather than panicking, I'd recommend logging diagnostics and then exiting the process with a non-zero exit code.

**Comment by glyn** [comment]
This happened when issuing `riff publish -d "hello riff"` many tens of times in parallel.

**Comment by scothis** [comment]
This issue has gone stale, we're on Knative now! Please reopen if still relevant.
