### ISSUE TITLE
riff create fail: "container name must be specified for pod..."

### ISSUE THREAD

**Issue by tony-kerz** [projectriff/riff#846]
osx: `10.13.6`

```
~  riff version                                                                                      157ms  Sun Sep 30 08:51:09 2018
Version
  riff cli: 0.1.3 (a216005db0d50056c41b45fdc3384b09ad24381d)
```

```
~/g/express-js-scratch   master *  minikube start --memory=8192 --cpus=3 \                         586ms  Sun Sep 30 08:56:57 2018
                                       --kubernetes-version=v1.10.5 \
                                       --vm-driver=hyperkit \
                                       --bootstrapper=kubeadm \
                                       --extra-config=apiserver.admission-control="LimitRanger,NamespaceExists,NamespaceLifecycle,ResourceQuota,ServiceAccount,DefaultStorageClass,MutatingAdmissionWebhook"
Starting local Kubernetes v1.10.5 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
Kubectl is now configured to use the cluster.
Loading cached images from config file.
```

```
~/g/express-js-scratch   master *  riff system install --node-port                                         Sun Sep 30 09:01:37 2018
Installing Istio components
Applying resources defined in: https://storage.googleapis.com/knative-releases/serving/previous/v20180921-69811e7/istio.yaml
Istio components installed

Waiting for the Istio components to start .......... all components are 'Running'

Installing Knative components
Applying resources defined in: https://storage.googleapis.com/knative-releases/serving/previous/v20180921-69811e7/release-no-mon.yaml
Applying resources defined in: https://storage.googleapis.com/knative-releases/eventing/previous/v20180921-01f95cb/release.yaml
Applying resources defined in: https://storage.googleapis.com/knative-releases/eventing/previous/v20180921-01f95cb/release-clusterbus-stub.yaml
Knative components installed

riff system install completed successfully
```

```
set -x DOCKER_ID {me}
```

```
 ~/g/express-js-scratch   master *  riff namespace init default --dockerhub $DOCKER_ID               1.5m  Sun Sep 30 09:03:22 2018
Initializing namespace "default"

Enter dockerhub password for user "{me}"
Creating secret "push-credentials" with DockerHub authentication for user "{me}"
Creating serviceaccount "riff-build" using secret "push-credentials" in namespace "default"
Applying https://storage.googleapis.com/riff-releases/previous/riff-build/riff-build-0.1.0.yaml in namespace "default"
buildtemplate.build.knative.dev/riff created

Applying https://storage.googleapis.com/riff-releases/riff-cnb-buildtemplate-0.1.0.yaml in namespace "default"
persistentvolumeclaim/riff-cnb-cache created
buildtemplate.build.knative.dev/riff-cnb created

riff namespace init completed successfully
```

```
 !  ~  riff function create node square \                                                            101ms  Sun Sep 30 09:11:10 2018
           --git-repo https://github.com/projectriff-samples/node-square  \
           --artifact package.json \
           --image $DOCKER_ID/square \
           --wait
```

```
!  ~  riff service invoke square --text -- -w '\n' -d 8                                             257ms  Sun Sep 30 09:14:16 2018
curl http://192.168.64.20:32380/ -H 'Host: square.default.example.com' -H 'Content-Type: text/plain' -w '\n' -d 8
64
```

```
~/g/express-js-scratch   master *  riff function create node express-js-scratch \                   7.9s  Sun Sep 30 09:05:11 2018
                                         --git-repo https://github.com/tony-kerz/express-js-scratch  \
                                         --artifact package.json \
                                         --image $DOCKER_ID/express-js-scratch \
                                         --wait
riff function create completed successfully
```

```
Every 1.0s: kubectl get pod --all-namespaces                                                    {my}.lan: Sun Sep 30 09:10:17 2018

NAMESPACE          NAME                                                   READY     STATUS             RESTARTS   AGE
default            express-js-scratch-00001-deployment-6cd5644c88-fqqth   2/3       CrashLoopBackOff   4          2m
default            express-js-scratch-00001-zzz8r                         0/1       Completed          0          3m
istio-system       istio-citadel-84fb7985bf-rvs9h                         1/1       Running            0          8m
istio-system       istio-cleanup-secrets-qcqpk                            0/1       Completed          0          8m
istio-system       istio-egressgateway-bd9fb967d-rtgmc                    1/1       Running            0          8m
istio-system       istio-galley-655c4f9ccd-sx5kx                          1/1       Running            0          8m
istio-system       istio-ingressgateway-688865c5f7-pnpcp                  1/1       Running            0          8m
istio-system       istio-pilot-6cd69dc444-6m5lh                           2/2       Running            0          8m
istio-system       istio-policy-6b9f4697d-tzzc7                           2/2       Running            0          8m
istio-system       istio-sidecar-injector-8975849b4-lhw6n                 1/1       Running            0          8m
istio-system       istio-statsd-prom-bridge-7f44bb5ddb-thkpn              1/1       Running            0          8m
istio-system       istio-telemetry-6b5579595f-cbps4                       2/2       Running            0          8m
istio-system       knative-ingressgateway-77b757d468-ks24t                1/1       Running            0          6m
knative-build      build-controller-7bd96569d-z592s                       1/1       Running            0          6m
knative-build      build-webhook-5c99bb9b99-g96cv                         1/1       Running            0          6m
knative-eventing   eventing-controller-59d55d8fd8-dhsmd                   1/1       Running            0          6m
knative-eventing   stub-clusterbus-dispatcher-c86bb6bff-ksn69             2/2       Running            0          6m
knative-eventing   webhook-c5878f4-8d5bl                                  1/1       Running            0          6m
knative-serving    activator-7d5b5ff75c-n4qr8                             2/2       Running            0          6m
knative-serving    autoscaler-86859bd685-hdvsm                            2/2       Running            0          6m
knative-serving    controller-5f66d69957-tfv58                            1/1       Running            0          6m
knative-serving    webhook-5b6cf589d7-n8zsl                               1/1       Running            0          6m
kube-system        coredns-c4cffd6dc-wlmhd                                1/1       Running            0          10m
kube-system        etcd-minikube                                          1/1       Running            0          9m
kube-system        kube-addon-manager-minikube                            1/1       Running            0          10m
kube-system        kube-apiserver-minikube                                1/1       Running            0          9m
kube-system        kube-controller-manager-minikube                       1/1       Running            0          10m
kube-system        kube-dns-86f4d74b45-svzph                              3/3       Running            0          10m
kube-system        kube-proxy-l6qt8                                       1/1       Running            0          10m
kube-system        kube-scheduler-minikube                                1/1       Running            0          9m
kube-system        kubernetes-dashboard-6f4cfc5d87-wg7qf                  1/1       Running            0          10m
kube-system        storage-provisioner                                    1/1       Running            0          10m
```

```
 ~/g/express-js-scratch   master *  k logs express-js-scratch-00001-zzz8r                            1.6m  Sun Sep 30 09:09:01 2018
Build successful
```

phew... and finally:

```
 ~  k logs express-js-scratch-00001-deployment-6cd5644c88-fqqth                                               Sun Sep 30 09:11:09 2018
Error from server (BadRequest): a container name must be specified for pod express-js-scratch-00001-deployment-6cd5644c88-fqqth, choose one of: [user-container queue-proxy istio-proxy] or one of the init containers: [istio-init]
```

i'm guessing it has something to do with the way this app uses the [node-config](https://github.com/lorenwest/node-config/blob/master/README.md) package, and the fact that the knative build process is unaware of it (note the way [my `build` script](https://github.com/tony-kerz/express-js-scratch/blob/ebc30e903819c486b14765234562491a528aa4f7/package.json#L16) copies the `config` folder into the `build` folder), so my app doesn't start correctly, but when i try to start locally without the `config` folder, i get the following:

```
 ~/g/express-js-scratch   master *  mv config config.bak                                                    Sun Sep 30 09:18:28 2018
 ~/g/express-js-scratch   master *…  yarn start                                                             Sun Sep 30 09:18:42 2018
yarn run v1.10.1
$ cross-env DEBUG=app:*,lib:*,dbg:* babel-watch src
WARNING: No configurations found in configuration directory:/Users/tony/git/express-js-scratch/config
WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.

/Users/tony/git/express-js-scratch/node_modules/@watchmen/helpr/dist/index.js:415
  (0, _assert3.default)(test, _lodash2.default.isFunction(message) ? message() : message);
                       ^
AssertionError [ERR_ASSERTION]: secret or public-key required
    at assert (/Users/tony/git/express-js-scratch/node_modules/@watchmen/helpr/dist/index.js:415:24)
    at Object.<anonymous> (/Users/tony/git/express-js-scratch/src/index.js:22:20)
    at Module._compile (module.js:653:30)
    at babelWatchLoader (/Users/tony/git/express-js-scratch/node_modules/babel-watch/runner.js:50:13)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/tony/git/express-js-scratch/node_modules/babel-watch/runner.js:61:7)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at process.on (/Users/tony/git/express-js-scratch/node_modules/babel-watch/runner.js:108:21)
```

i will initially address the above by allowing the app to handle absence of the `config` folder more gracefully, but i have two related questions:

1. where would i look for the above `AssertionError` in riff/knative when in troubleshooting mode?
1. what are my strategies for tweaking the knative build to account for additional resources such as the `config` folder if desired?

> by the way, after having spent some time with the knative documentation trying to wrap my head around how to kick-the-tires, i *really* appreciate the way riff packages it all up in a more accessible way, so *kudos!*

*update:* i fixed the `config` issue such that the app doesn't require it, but i am witnessing the same result. my next guess is the use of babel, not sure how knative-build plays with that. tips welcome ;)

*update:* having found and perused the [node-function-invoker](https://github.com/projectriff/node-function-invoker), i can see that my initial effort to pass in an express app as a function was ill-informed and that may well be one of my issues (although i'm still interested in [patterns for exposing a rest-ful api powered by functions](https://github.com/awslabs/aws-serverless-express)), but i'm still seeking tips around troubleshooting and strategies for customizing the build process...

**Comment by scothis** [comment]
Hi @tony-kerz, welcome to riff 👋

The initial error you saw isn't from the logs, but from the Kubernetes API server when trying to load the logs. Since there are multiple containers in the pod, you need to specify which container to get logs for. In this case, the `user-container` has the logs for your code.

Try running:
```
k logs express-js-scratch-00001-deployment-6cd5644c88-fqqth -c user-container
```

Now on to the actual issue. The node-function-invoker has two primary styles that it supports: request-reply and streams.

With request-reply functions, the function accepts a single input and returns a single output. For example, a function that squares a number looks like `x => x ** 2`. The invoker wraps this function and exposes it over http. At its core, the invoker accepts a request at `POST /`, unmarshals the request based on the content-type header, calls the function, takes the response and marshals it based on the accept header. You don't need to use a library like express, as a function generally should not need to concern itself with http. Under the hood the invoker uses express,. but that's an implementation detail.

The [readme for the node-function-invoker](https://github.com/projectriff/node-function-invoker#functions) has the best documentation and examples of what is supported right now.

**Comment by scothis** [comment]
Building a restful api out of functions is a use case we'd like to support, and will involve deploying an API gateway that will map restful http requests into function calls.

**Comment by tony-kerz** [comment]
hi scott, 

thanks much for the 411, that is very helpful.

so, if i had an api-gateway (e.g. embassador) and a created function (e.g. `square`), 
can i map a rest call to a function call today, or are there some pending implementation details
currently making that impractical (trying to parse your words "we'd like to support"...)

best,
tony.

**Comment by scothis** [comment]
> so, if i had an api-gateway (e.g. embassador) and a created function (e.g. square),
can i map a rest call to a function call today, or are there some pending implementation details
currently making that impractical (trying to parse your words "we'd like to support"...)

The short answer is that we haven't tested any gateways, but if the gateway can make an http post to a  the hostname for the square function it should work.
