### ISSUE TITLE
Function deploy error to Minikube and GKE: IllegalStateException: Cannot create bean

### ISSUE THREAD

**Issue by cjaehnen** [projectriff/riff#996]
Hello, I'm trying to deploy a Kotlin-based Spring Cloud Function to my GKE via riff. I have everything setup correctly, I believe, following the guide: https://projectriff.io/docs/getting-started/gke/

I'm compiling the Kotlin code into a Java jar then attempting to create my function via the command:

```bash
riff function create bank-function-save-transaction \
>   --local-path applications/save-transaction-function-service/build/libs \
>   --artifact save-transaction-function-service-0.0.1-SNAPSHOT.jar \
>   --handler io.opengood.cloudnative.function.bankfunctionservice.savetransaction.function.SaveTransaction \
>   --image gcr.io/opengood-io/bank-function-save-transaction:v1 \
>   --invoker java \
>   --verbose
```

However, I'm getting this error:

```
IllegalStateException: Cannot create bean for: io.opengood.cloudnative.function.bankfunctionservice.savetransaction.function.SaveTransaction
```

I'm not sure what to make of the error. I bootrun the functions locally via Spring Boot and it works fine.

Here's my GitHub repo: https://github.com/opengood-io/bank-function-services

Output:

```bash
2018/12/05 20:53:34 Pulling builder image 'projectriff/builder' (use --no-pull flag to skip this step)
2018/12/05 20:53:35 Using user provided run image 'packs/run'
*** DETECTING:
2018/12/06 01:53:39 Group: Cloud Foundry OpenJDK Buildpack: pass | Node.js Buildpack: pass | Cloud Foundry Build System Buildpack: fail | NPM Buildpack: fail | riff Buildpack: pass
*** ANALYZING: Reading information from previous image for possible re-use
*** BUILDING:
-----> Cloud Foundry OpenJDK Buildpack 1.0.0-M1
-----> OpenJDK JRE 1.8.192: Reusing cached launch layer


-----> riff Buildpack 0.1.1-BUILD-SNAPSHOT
-----> riff Java Invoker 0.1.3: Reusing cached launch layer
-----> Process types:
       web:      java -jar /workspace/io.projectriff.riff/riff-invoker-java/java-function-invoker-0.1.3-exec.jar $JAVA_OPTS --function.uri='file:///workspace/app?handler=io.opengood.cloudnative.function.bankfunctionservice.savetransaction.function.SaveTransaction'
       function: java -jar /workspace/io.projectriff.riff/riff-invoker-java/java-function-invoker-0.1.3-exec.jar $JAVA_OPTS --function.uri='file:///workspace/app?handler=io.opengood.cloudnative.function.bankfunctionservice.savetransaction.function.SaveTransaction'

*** EXPORTING:
2018/12/05 20:53:59 existing blob: sha256:c46b5fa4d940569e49988515c1ea0295f56d0a16228d8f854e27613f467ec892
2018/12/05 20:53:59 existing blob: sha256:176eb75e6a82518a7a018cf0ba5a7c666caeae6d0c1726f1637459e5d20affe3
2018/12/05 20:53:59 existing blob: sha256:b049a4c480366995486b3029899acf64e7efbd647154a3344237931677492810
2018/12/05 20:53:59 existing blob: sha256:93ae3df89c92cb1d20e9c09f499e693d3a8a8cef161f7158f7a9a3b5d06e4ef2
2018/12/05 20:53:59 existing blob: sha256:6b1eed27cadec5de8051d56697b0b67527e4076deedceefb41b7b2ea9b900459
2018/12/05 20:53:59 existing blob: sha256:406c26bca4d2bd2bafb14f1854fed1cbfbaeb853f3e4cbb11487db336f8cd2a4
2018/12/05 20:53:59 existing blob: sha256:473ede7ed136b710ab2dd51579af038b7d00fbbf6a1790c6294c93666203c0a6
2018/12/05 20:53:59 existing blob: sha256:7e9028e3c5c10cb0b2a4fa08c6b148eb1fc41f8d65e1eb3677de6efb6d3e3ac2
2018/12/05 20:53:59 existing blob: sha256:896d6a42b4a26a7a999c372b16c14fff84ff77f95aa9e758873d415b30a09efb
2018/12/05 20:53:59 existing blob: sha256:6a2a6ba536090808ee55195ea3b2951a0ec2d303339dce68bcaae42c8f4eacc6
2018/12/05 20:53:59 existing blob: sha256:20d3d07c8f94c2b57c94a3fc0e61485c9e6317a319e902f8c3650de879df7787
2018/12/05 20:53:59 existing blob: sha256:d295e17f566a019ff16ec3179a435c0e72b18355e540f4c8a132afba83770ac7
2018/12/05 20:54:02 pushed blob sha256:b61b4eeb4e3c89c43ff6adc63121cf27a9f1ba3a80f06cd9c55641015c5625b6
2018/12/05 20:54:03 pushed blob sha256:8045beef4167142246b88a6bf8a3dd7304c2e2daaed68c04dd6d57286fd4f8bb
2018/12/05 20:54:06 pushed blob sha256:3c1b2c1f6957e922f80c9e24f8bd258638b656064e6d4bc9d3d5dad157f396ef
2018/12/05 20:54:07 gcr.io/opengood-io/bank-function-save-transaction:v1: digest: sha256:11dc3aa71930f0ff4c42800d59124c225eae834c8590bc4a5df5b8dfc8f52d70 size: 2538
2018/12/05 20:54:07
*** Image: gcr.io/opengood-io/bank-function-save-transaction:v1@sha256:11dc3aa71930f0ff4c42800d59124c225eae834c8590bc4a5df5b8dfc8f52d70
Waiting for LatestCreatedRevisionName
Waiting on function creation: function creation incomplete: service status unknown: RevisionMissing: Configuration "bank-function-save-transaction" is waiting for a Revision to become ready.
LatestCreatedRevisionName available: bank-function-save-transaction-00001
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]:
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]:                 ?      ????????????
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]:                 ???    ??  ????  ??
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]:                ???? ??????????????
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]:               ?????   ???    ??
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]:    ?????????  ??      ???    ??
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]:     ???   ??  ??      ???    ??
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]:     ???       ??     ?????  ?????
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]:     ???       ??
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]:    ??????
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]:
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: :: Powered by Spring Boot ::
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: Dec 06, 2018 1:54:27 AM org.springframework.boot.StartupInfoLogger logStarting
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: INFO: Starting application on bank-function-save-transaction-00001-deployment-59969c67cddh824 with PID 1 (/workspace/io.projectriff.riff/riff-invoker-java/java-function-invoker-0.1.3-exec.jar started by pack in /workspace/app)
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: Dec 06, 2018 1:54:27 AM org.springframework.boot.SpringApplication logStartupProfileInfo
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: INFO: No active profile set, falling back to default profiles: default
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: Dec 06, 2018 1:54:29 AM org.springframework.boot.web.embedded.tomcat.TomcatWebServer initialize
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: INFO: Tomcat initialized with port(s): 8080 (http)
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: Dec 06, 2018 1:54:29 AM org.apache.catalina.core.StandardService startInternal
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: INFO: Starting service [Tomcat]
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: Dec 06, 2018 1:54:29 AM org.apache.catalina.core.StandardEngine startInternal
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: INFO: Starting Servlet Engine: Apache Tomcat/9.0.12
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: Dec 06, 2018 1:54:29 AM org.apache.catalina.core.AprLifecycleListener lifecycleEvent
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: INFO: The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/workspace/org.cloudfoundry.openjdk/openjdk-jre/lib:/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib]
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: Dec 06, 2018 1:54:30 AM org.apache.catalina.core.ApplicationContext log
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: INFO: Initializing Spring embedded WebApplicationContext
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: Dec 06, 2018 1:54:30 AM org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext prepareWebApplicationContext
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: INFO: Root WebApplicationContext: initialization completed in 2307 ms
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: Dec 06, 2018 1:54:30 AM org.springframework.boot.web.servlet.ServletRegistrationBean addRegistration
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: INFO: Servlet dispatcherServlet mapped to [/]
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: Dec 06, 2018 1:54:30 AM org.springframework.boot.web.servlet.AbstractFilterRegistrationBean configure
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: INFO: Mapping filter: 'characterEncodingFilter' to: [/*]
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: Dec 06, 2018 1:54:30 AM org.springframework.boot.web.servlet.AbstractFilterRegistrationBean configure
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: INFO: Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: Dec 06, 2018 1:54:30 AM org.springframework.boot.web.servlet.AbstractFilterRegistrationBean configure
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: INFO: Mapping filter: 'formContentFilter' to: [/*]
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: Dec 06, 2018 1:54:30 AM org.springframework.boot.web.servlet.AbstractFilterRegistrationBean configure
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: INFO: Mapping filter: 'requestContextFilter' to: [/*]
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: Dec 06, 2018 1:54:30 AM org.springframework.cloud.function.deployer.FunctionCreatorConfiguration init
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: INFO: Locating function from [file:///workspace/app]
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: Dec 06, 2018 1:54:30 AM org.springframework.cloud.function.deployer.FunctionCreatorConfiguration$BeanCreator create
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: INFO: No bean found. Instantiating: io.opengood.cloudnative.function.bankfunctionservice.savetransaction.function.SaveTransaction
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: Dec 06, 2018 1:54:30 AM org.springframework.context.support.AbstractApplicationContext refresh
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: WARNING: Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cloud.function.deployer.FunctionCreatorConfiguration': Invocation of init method failed; nested exception is java.lang.IllegalStateException: Cannot create functions
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: Dec 06, 2018 1:54:30 AM org.apache.catalina.core.StandardService stopInternal
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: INFO: Stopping service [Tomcat]
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: Dec 06, 2018 1:54:30 AM org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener logMessage
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: INFO:
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: Exception in thread "main" java.lang.reflect.InvocationTargetException
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: 	at java.lang.reflect.Method.invoke(Method.java:498)
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cloud.function.deployer.FunctionCreatorConfiguration': Invocation of init method failed; nested exception is java.lang.IllegalStateException: Cannot create functions
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:139)
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:419)
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1737)
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:576)
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498)
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:846)
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:863)
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: 	at org.springframework.cloud.function.deployer.ContextRunner$1.run(ContextRunner.java:65)
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: 	at java.lang.Thread.run(Thread.java:748)
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: Caused by: java.lang.IllegalStateException: Cannot create functions
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: 	at org.springframework.cloud.function.deployer.FunctionCreatorConfiguration.init(FunctionCreatorConfiguration.java:136)
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: 	at java.lang.reflect.Method.invoke(Method.java:498)
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:363)
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:307)
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: 	... 17 more
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: Caused by: java.lang.IllegalStateException: Cannot create bean for: io.opengood.cloudnative.function.bankfunctionservice.savetransaction.function.SaveTransaction
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: 	at org.springframework.cloud.function.deployer.FunctionCreatorConfiguration$BeanCreator.create(FunctionCreatorConfiguration.java:492)
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: 	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: 	at org.springframework.cloud.function.deployer.FunctionCreatorConfiguration.init(FunctionCreatorConfiguration.java:126)
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: 	... 24 more
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]:
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]:                 ?      ????????????
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]:                 ???    ??  ????  ??
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]:                ???? ??????????????
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]:               ?????   ???    ??
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]:    ?????????  ??      ???    ??
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]:     ???   ??  ??      ???    ??
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]:     ???       ??     ?????  ?????
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]:     ???       ??
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]:    ??????
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]:
default/bank-function-save-transaction-00001-deployment-59969c67cddh824[user-container]: :: Powered by Spring Boot ::

riff function create completed successfully
```

**Comment by ericbottard** [comment]
Functions in riff are now built from source, thus you should not try to set `--artifact` to a pre-built jar file. So, something like this should work:
```
riff function create bank-function-save-transaction \
   --local-path applications/save-transaction-function-service/build/libs \
   --handler io.opengood.cloudnative.function.bankfunctionservice.savetransaction.function.SaveTransaction \
   --image gcr.io/opengood-io/bank-function-save-transaction:v1 \
   --verbose
```

(or with `--git-repo https://github.com/opengood-io/bank-function-services`)


__However__, the [Build System Buildpack](https://github.com/cloudfoundry/build-system-buildpack) which is used by riff to build JVM based apps (maven / gradle) currently doesn't support `build.gradle` files written in kotlin (doesn't detect them). I created https://github.com/cloudfoundry/build-system-buildpack/issues/3 to track this.

If you are eager to try riff nonetheless until this is fixed, you could try to rewrite your build file in groovy and see how far you go.

**Comment by cjaehnen** [comment]
@ericbottard thanks for the info! I took your suggestions and built the function from source using:

```bash
riff function create bank-function-save-transaction \
  --local-path . \
  --handler io.opengood.cloudnative.function.bankfunctionservice.savetransaction.function.SaveTransaction \
  --image gcr.io/opengood-io/bank-function-save-transaction:v1 \
  --verbose
```

However, I'm stilling the same error:

```
IllegalStateException: Cannot create bean for: io.opengood.cloudnative.function.bankfunctionservice.savetransaction.function.SaveTransaction
```

I also tried this on a local Minikube instance and get the same error.

**Comment by cjaehnen** [comment]
Ok, I've made some progress. I now get this error:

```
aused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'io.opengood.cloudnative.function.bank.transaction.save.repository.TransactionRepository' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1646)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1205)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1166)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:855)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:758)
	... 40 more
```

after running:

```bash
riff function create bank-save-transaction \
  --local-path . \
  --handler io.opengood.cloudnative.function.bank.transaction.save.function.SaveTransaction \
  --image gcr.io/opengood-io/bank-save-transaction:v1 \
  --verbose
```

It's not finding my Spring config beans configured through my Kotlin application main class `ApplicationKt`.

I'm using constructor injection in my function. Do I need to use `@Autowire` instead to inject my Spring bean dependency?

FYI. I renamed my Git repo and it is now found at: https://github.com/opengood-io/bank-save-transaction-function-service
